#!/bin/sh

cd "$( dirname "${BASH_SOURCE[0]}" )"
cd ..

function build_site {
	if [[ $1 == "v1."* ]]; then
		mkdir -p dist
		touch dist/index.html
	else
		NODE_VERSION="18.16.0"

		if [[ $(which node) == "" || $(node -v) != "v$NODE_VERSION" ]]; then
			if [ $(which nvm) == "" ]; then
				echo "nvm not installed, installing..."
				install_nvm
			fi

			echo "Installing node $NODE_VERSION"
			nvm install $NODE_VERSION
			nvm use $NODE_VERSION
			
			echo "Installing yarn"
			npm install -g yarn
		fi

		echo "Installing dependencies"
		yarn install

		echo "Building webpack"
		yarn build
	fi
}

function install_nvm {
	apt install -y curl
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
	bash "$HOME/.nvm/nvm.sh"
}

CURRENT_BRANCH=$(git branch --show-current)
CURRENT_DETHEAD_VALUE=$(git config advice.detachedHead)
git config advice.detachedHead false

function clean_up {
	git checkout $CURRENT_BRANCH
	git config advice.detachedHead "$CURRENT_DETHEAD_VALUE"
}

function on_exit() {
	echo "Program is exiting, cleaning up"
	clean_up
	exit 0
}

function on_error() {
	echo "Program has errored, cleaning up"
	clean_up
	rm -rf $BUILD_DIR
	rm -rf dist
	exit 1
}

trap on_error ERR
trap on_exit SIGINT

BUILD_DIR="docker-build"
rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR

echo "Fetching site versions"
site_versions=( `git tag` staging )
current_version=`git describe --tags --abbrev=0`
echo "Current version is $current_version"

for version in "${site_versions[@]}"
do
	echo "Checking out version $version"
	git checkout $version

	echo "Building site version $version"
	build_site $version

	version_dir_name=${version//./_}
	version_dir="$BUILD_DIR/$version_dir_name"
	mkdir -p $version_dir
	echo "Copying build to $version_dir"
	cp -r dist/* $version_dir

	rm -rf dist

	echo "Finished building version $version"
done

clean_up
