#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

function clean_up() {
	rm -rf $OUT_DIR
}

function on_exit() {
	echo "Program is exiting, cleaning up"
	clean_up
	exit 0
}

function on_error() {
	echo "Program has errored, cleaning up"
	clean_up
	exit 1
}

trap on_error ERR
trap on_exit SIGINT

if [ -z "$1" ]; then
	echo "Please specify a tool to run"
	exit 1
fi

OUT_DIR="$(pwd)/cache"
FILENAME=$1
FILENAME_TS="$1.ts"
FILENMAE_JS="$1.js"

if [ ! -f "tools/$FILENAME_TS" ]; then
	echo "$FILENAME tool does not exist"
	exit 1
fi

echo "Compiling tools"
yarn tsc -p $(pwd)/tsconfig.tools.json --outDir $OUT_DIR

echo "Running tool $FILENAME"
node $OUT_DIR/$FILENMAE_JS

echo "Finished running tool $FILENAME, cleaning up"
clean_up
